import {StyleSheet} from "react-native";

export const stylesForumCard = StyleSheet.create({
    forumCardContainer: {
        paddingTop: 6,
        paddingRight: 18,
        paddingBottom: 34,
        paddingLeft: 18,
    },
    postedDateContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    postedDateIcon: {
        width: 6,
        height: 6,
    },
    postedDate: {
        color: '#828282',
        fontSize: 6,
        fontStyle: 'normal',
        fontWeight: '300',
        marginLeft: 6,
    },

    forumCardUserContainer: {
        display: 'flex',
        flexDirection: 'row',
        marginTop: 12,
    },
    userStory: {
        width: 68,
        height: 68,
        borderRadius: 50,
        backgroundColor: '#E0E0E0',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        width: 58,
        height: 58,
        borderRadius: 50,
        resizeMode: 'cover',
    },
    userImageContent: {
        backgroundColor: '#fff',
        borderRadius: 50,
        padding: 2,
    },
    userFaceInfo: {},
    userName: {
        color: '#4F4F4F',
        textAlign: 'center',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '500',
        marginTop: 4,
    },

    userInformation: {
        marginLeft: 16,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
    },
    forumCardQuestion: {
        color: '#4F4F4F',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '500',
    },

    forumCardAnswerAndViews: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 8,
    },
    forumCardAnswer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    forumCardAnswerIcon: {
        width: 12,
        height: 8,
    },
    forumCardAnswerLabel: {
        color: '#828282',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '300',
        marginLeft: 4,
    },
    forumCardViews: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginLeft: 26,
    },
    forumCardViewsIcon: {
        width: 12,
        height: 8,
    },
    forumCardViewsLabel: {
        color: '#828282',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '300',
        marginLeft: 4,
    },
    forumTagsCardContainer: {
        width: 'auto',
        height: 20,
        borderRadius: 100,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        backgroundColor:'#F8F8F8',
        paddingTop: 4,
        paddingLeft: 8,
        paddingBottom: 4,
        paddingRight: 8,
        marginLeft: 4,
        marginRight: 4,
    },
    forumTagsCardName: {
        color: '#828282',
        textAlign: 'center',
        fontSize: 8,
        fontStyle: 'normal',
        fontWeight: '300',
    },
    forumCardTags: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginTop: 14,
    },
    forumCardButtons: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 38,
    },
    forumCardBtnBrowseContainer: {
        width: 106,
        height: 34,
        borderWidth: 1,
        borderRadius: 100,
        backgroundColor: '#F8F8F8',
        borderColor: '#E0E0E0',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    forumCardBtnBrowseName: {
        color: '#BDBDBD',
        textAlign: 'center',
        fontSize: 14,
        fontWeight: '400',
    },
    forumCardBtnReplyContainer: {
        width: 106,
        height: 34,
        borderRadius: 100,
        backgroundColor: '#DE4878',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 14,
    },
    forumCardBtnReplyName: {
        color: '#FFF',
        textAlign: 'center',
        fontSize: 14,
        fontWeight: '400',
    },
});
