import {StyleSheet} from "react-native";

export const stylesForumCardWriteReply = StyleSheet.create({
    browserInformationContent: {
        paddingLeft: 16,
        paddingRight: 16,
    },
    browserInformationText: {
        color: '#828282',
        textAlign: 'center',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '400',
        lineHeight: 24,
    },
    writeReplyContainer: {
        paddingLeft: 18,
        paddingTop: 18,
        paddingRight: 18,
        paddingBottom: 18,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    writeReplyUserContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    writeReplyUserIcon: {
        width: 28,
        height: 28,
        borderRadius: 50,
    },
    writeReplyUserInfo: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginLeft: 10,
    },
    writeReplyUserName: {
        color: '#4F4F4F',
        fontSize: 12,
        fontStyle: 'normal',
        fontWeight: '400',
    },
    writeReplyUserStatusContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        marginTop: 4,
    },
    writeReplyUserStatusText: {
        color: '#828282',
        fontSize: 8,
        fontStyle: 'normal',
        fontWeight: '300',
    },
    writeReplyUserStatusIcon: {
        width: 8,
        height: 8,
        marginLeft: 6,
    },
    writeReplyInputContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginTop: 16,
        marginLeft: 40,
    },
    writeReplyInput: {
        width: 221,
        height: 30,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        backgroundColor: 'rgba(196, 196, 196, 0.00)',
        color: '#828282',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '100',
        paddingLeft: 18,
    },
    writeReplySaveBtnContainer: {
        backgroundColor: '#DE4878',
        marginLeft: 2,
    },
    writeReplySaveBtn: {
        paddingLeft: 16,
        paddingTop: 8,
        paddingRight: 16,
        paddingBottom: 8,
    },
    writeReplySaveBtnText: {
        color: '#FFF',
        textAlign: 'center',
        fontSize: 10,
        fontStyle: 'normal',
        fontWeight: '400',
    },
});
